SIGN_UP_BUTTON = "[data-test-id=\"PRIMARY_CTA\"]"

SELECT_SUBSCRIPTION_PLAN_PAGE = "[data-test-id=\"select-subscription__page\"]"
PLAN_DETAILS_ANNUAL = "[data-test-id=\"plan-details__wrapper_Annual\"]"
PLAN_DETAILS_MONTHLY = "[data-test-id=\"plan-details__wrapper_Month\"]"
PLAN_DETAILS_REGULAR_BUTTON = "[data-test-id=\"plan-details__button\"]"
PLAN_DETAILS_DCB_BUTTON = "[data-test-id=\"plan-details__dcb-button\"]"

CREATE_ACCOUNT_PAGE = "[data-test-id=\"create-account__page\"]"
FIRST_NAME_FIELD = "[data-test-id=\"FIRST_NAME\"]"
LAST_NAME_FIELD = "[data-test-id=\"LAST_NAME\"]"
EMAIL_FIELD = "[data-test-id=\"EMAIL\"]"
CONFIRM_EMAIL_FIELD = "[data-test-id=\"CONFIRM_EMAIL\"]"
PASSWORD_FIELD = "[data-test-id=\"PASSWORD\"]"
CREATE_ACCOUNT_BUTTON = "[data-test-id=\"create-account__button\"]"

FREE_TRIAL_BANNER = "[data-test-id=\"MODAL_NOTIFICATION_undefined\"]"
FREE_TRIAL_DISMISS_BUTTON = "[data-test-id=\"DIALOG_BUTTON-0\"]"

SELECT_PAYMENT_PAGE = "[data-test-id=\"select-payment__page\"]"
CREDIT_CARD_PAYMENT_METHOD = "[data-test-id=\"select-payment__option__CreditCard_Button\"]"
CREDIT_CARD_NUMBER_FIELD = "[data-test-id=\"encryptedCardNumber\"]"
CREDIT_CARD_NUMBER_FIELD_ID = "encryptedCardNumber"
CREDIT_CARD_EXPIRY_MONTH_FIELD = "[data-test-id=\"encryptedExpiryMonth\"]"
CREDIT_CARD_EXPIRY_MONTH_FIELD_ID = "encryptedExpiryMonth"
CREDIT_CARD_EXPIRY_YEAR_FIELD = "[data-test-id=\"encryptedExpiryYear\"]"
CREDIT_CARD_EXPIRY_YEAR_FIELD_ID = "encryptedExpiryYear"
CREDIT_CARD_SECURITY_CODE_FIELD = "[data-test-id=\"encryptedSecurityCode\"]"
CREDIT_CARD_SECURITY_CODE_FIELD_ID = "encryptedSecurityCode"
CREDIT_CARD_STREET_FIELD = "billing-address-street"
CREDIT_CARD_HOUSE_NUMBER_FIELD = "billing-address-houseNumberOrName"
CREDIT_CARD_POSTAL_CODE_FIELD = "billing-address-postalCode"
CREDIT_CARD_CITY_FIELD = "billing-address-city"
CREDIT_CARD_SUBMIT_BUTTON = "[data-test-id=\"adyenCreditCardSubmitButton\"]"
GIFTCODE_PAYMENT_METHOD = "[data-test-id=\"select-payment__option__GiftCode_Button\"]"
GIFT_CODE_FIELD = "[data-test-id=\"GIFT_CODE\"]"

SIGN_UP_CONFIRMATION_PAGE = "[data-test-id=\"signUpConfirmation__PAGE\"]"
SIGN_UP_CONFIRMATION_BUTTON = "[data-test-id=\"signUpConfirmation__BUTTON\"]"
