MAIN_URL = "https://stag.dazn.com"
SIGN_IN_URL = "https://stag.dazn.com/account/signin"
PAYMENT_PLAN_URL = "https://stag.dazn.com/account/payment-plan"
SIGN_UP_URL = "https://stag.dazn.com/account/signup"
FAVOURITES_ENDPOINT = "favourites.discovery.dazn-stage.com/v2/events"
REMINDERS_ENDPOINT = "favourites.discovery.dazn-stage.com/v2/reminders"
RAIL_HOST = "rail.discovery.dazn-stage.com"
RAILS_HOST = "rails.discovery.dazn-stage.com"
